"""Product catalog data for Naturis Marketplace (Goshen Giant Foods Ltd)."""

PRODUCTS = [
    {
        "id": "egusi-whole",
        "name": "Premium Whole Melon Seeds (Egusi)",
        "size": "4.4 lb / 2 kg",
        "kg": 2,
        "qty": 10,
        "unit": "packs",
        "price": 21.0,
        "dist": 18.9,
        "initial": "EG",
        "description": "Hand-selected Nigerian whole melon seeds, carefully sun-dried to preserve their natural oils and nutty flavour. A traditional thickener for West African soups.",
        "ingredients": "100% whole melon seeds (Citrullus lanatus).",
        "diet": "Plant-based, vegan, vegetarian, gluten-free, keto-friendly.",
        "packaging": "Multi-layer stand-up pouch with resealable zip closure; 10 pouches per double-wall master carton.",
        "storage": "Keep cool and dry; reseal tightly after opening, or refrigerate to protect freshness.",
        "allergens": "Packaged in a facility that handles fish and crustacean shellfish.",
        "use": "Grind for traditional egusi soup, or toast lightly as a salad topping.",
        "source": "Smallholder farmers in North-Central Nigeria.",
        "retail": {
            "size": "2.2 lb / 1 kg",
            "kg": 1,
            "qty": 20,
            "unit": "packs",
            "price": 11.5,
        },
    },
    {
        "id": "egusi-ground",
        "name": "Premium Ground Melon Seeds (Egusi)",
        "size": "2.2 lb / 1 kg",
        "kg": 1,
        "qty": 20,
        "unit": "packs",
        "price": 12.0,
        "dist": 10.8,
        "initial": "GM",
        "description": "Finely ground melon seeds for rich traditional flavour with quick, convenient preparation.",
        "ingredients": "100% ground melon seeds.",
        "diet": "Plant-based, vegan, vegetarian, gluten-free, keto-friendly.",
        "packaging": "Resealable foil-laminate barrier pouch; 20 pouches per master carton.",
        "storage": "Seal tightly and refrigerate after opening to protect natural oils.",
        "allergens": "Facility also handles fish and crustacean shellfish.",
        "use": "Mix with warm water and add to an egusi soup base.",
        "source": "Farming cooperatives in Nigeria.",
        "retail": {
            "size": "1.1 lb / 500 g",
            "kg": 0.5,
            "qty": 40,
            "unit": "packs",
            "price": 6.5,
        },
    },
    {
        "id": "cray-whole",
        "name": "Premium Whole Crayfish",
        "size": "2.2 lb / 1 kg",
        "kg": 1,
        "qty": 10,
        "unit": "packs",
        "price": 24.5,
        "dist": 22.05,
        "initial": "WC",
        "description": "Whole dried coastal crayfish with a savoury seafood flavour for West African cooking.",
        "ingredients": "100% dried crayfish (Parapenaeopsis atlantica).",
        "diet": "Pescatarian, high-protein, keto-friendly, gluten-free.",
        "packaging": "Vacuum-sealed barrier pouch; 10 packs per master carton.",
        "storage": "Keep cool and dry; refrigerate or freeze after opening.",
        "allergens": "Contains crustacean shellfish (crayfish).",
        "use": "Grind into Afang, ogbono, seafood okra or rice dishes.",
        "source": "Wild-caught coastal harvest.",
        "retail": {
            "size": "1.1 lb / 500 g",
            "kg": 0.5,
            "qty": 40,
            "unit": "packs",
            "price": 13.0,
        },
    },
    {
        "id": "cray-ground",
        "name": "Premium Ground Crayfish",
        "size": "2.2 lb / 1 kg",
        "kg": 1,
        "qty": 10,
        "unit": "packs",
        "price": 27.0,
        "dist": 24.3,
        "initial": "GC",
        "description": "Finely ground dried crayfish, ready to add savoury depth to soups, rice and stews.",
        "ingredients": "100% ground dried crayfish.",
        "diet": "Pescatarian, high-protein, keto-friendly, gluten-free.",
        "packaging": "Vacuum-sealed barrier pouch; 10 packs per master carton.",
        "storage": "Keep dry and refrigerate after opening.",
        "allergens": "Contains crustacean shellfish.",
        "use": "Sprinkle into jollof rice, yam porridge and soups.",
        "source": "Coastal fishing communities.",
        "retail": {
            "size": "14 oz / 400 g",
            "kg": 0.4,
            "qty": 50,
            "unit": "packs",
            "price": 11.5,
        },
    },
    {
        "id": "catfish",
        "name": "Authentic African Smoked Catfish",
        "size": "4.4 lb / 2 kg",
        "kg": 2,
        "qty": 5,
        "unit": "packs",
        "price": 34.0,
        "dist": 30.6,
        "initial": "CF",
        "description": "Cleaned, gutted African catfish traditionally hardwood-smoked for a rich flavour. Bone-in whole pieces.",
        "ingredients": "Catfish (Clarias gariepinus), natural wood smoke, salt.",
        "diet": "Pescatarian, high-protein, keto-friendly, sugar-free.",
        "packaging": "Vacuum-sealed pack; 5 packs per moisture-resistant master carton.",
        "storage": "Shelf-stable while unopened when stored as directed on the finished pack. Refrigerate or freeze immediately after opening. Follow the package best-before date.",
        "allergens": "Contains fish (catfish).",
        "use": "Soften in hot water, then add to bitterleaf, efo riro or banga soup.",
        "source": "Nigerian aquaculture farms.",
        "retail": {
            "size": "2.2 lb / 1 kg",
            "kg": 1,
            "qty": 20,
            "unit": "packs",
            "price": 18.5,
        },
    },
    {
        "id": "garri-white",
        "name": "Crispy White Garri",
        "size": "11 lb / 5 kg",
        "kg": 5,
        "qty": 4,
        "unit": "bags",
        "price": 15.0,
        "dist": 13.5,
        "initial": "WG",
        "description": "Dry-roasted fermented cassava grains with a crisp texture and characteristic pleasantly sour taste.",
        "ingredients": "100% fermented cassava root (Manihot esculenta).",
        "diet": "Vegan, vegetarian, plant-based, gluten-free.",
        "packaging": "Woven polypropylene bag with inner liner; 4 bags per master carton.",
        "storage": "Keep sealed in a dry cupboard at room temperature.",
        "allergens": "May contain traces of fish or shellfish from shared facility handling.",
        "use": "Stir into boiling water for eba, or soak for a chilled garri drink.",
        "source": "Nigerian cassava farms.",
        "retail": {
            "size": "4.4 lb / 2 kg",
            "kg": 2,
            "qty": 10,
            "unit": "bags",
            "price": 6.5,
        },
    },
    {
        "id": "garri-yellow",
        "name": "Premium Yellow Garri",
        "size": "11 lb / 5 kg",
        "kg": 5,
        "qty": 4,
        "unit": "bags",
        "price": 16.5,
        "dist": 14.85,
        "initial": "YG",
        "description": "Fermented cassava grains roasted with red palm oil for a golden colour and traditional flavour.",
        "ingredients": "Fermented cassava root, red palm oil.",
        "diet": "Vegan, vegetarian, plant-based, gluten-free.",
        "packaging": "Laminated woven polypropylene bag; 4 bags per master carton.",
        "storage": "Store cool and dry away from water.",
        "allergens": "Facility may also handle fish and shellfish.",
        "use": "Prepare yellow eba to serve with ogbono or egusi soup.",
        "source": "Cassava sourced in Southern Nigeria.",
        "retail": {
            "size": "4.4 lb / 2 kg",
            "kg": 2,
            "qty": 10,
            "unit": "bags",
            "price": 7.0,
        },
    },
    {
        "id": "yam",
        "name": "Elubo Yam Flour",
        "size": "4.4 lb / 2 kg",
        "kg": 2,
        "qty": 10,
        "unit": "packs",
        "price": 8.5,
        "dist": 7.65,
        "initial": "YF",
        "description": "Parboiled and milled dehydrated yam flour for traditional dark amala.",
        "ingredients": "100% dehydrated white yam (Dioscorea alata).",
        "diet": "Vegan, vegetarian, gluten-free, plant-based.",
        "packaging": "Resealable barrier pouch; 10 packs per master carton.",
        "storage": "Seal tightly and store in a dry pantry.",
        "allergens": "See finished pack for allergen handling statement.",
        "use": "Whisk into boiling water until smooth for amala.",
        "source": "Nigerian yam-growing regions.",
        "retail": {
            "size": "2.2 lb / 1 kg",
            "kg": 1,
            "qty": 20,
            "unit": "packs",
            "price": 4.5,
        },
    },
    {
        "id": "plantain",
        "name": "Premium Plantain Flour",
        "size": "4.4 lb / 2 kg",
        "kg": 2,
        "qty": 10,
        "unit": "packs",
        "price": 10.5,
        "dist": 9.45,
        "initial": "PF",
        "description": "Finely milled green plantain flour for swallow and selected baking recipes.",
        "ingredients": "100% unripened green plantain (Musa paradisiaca).",
        "diet": "Vegan, gluten-free; low-glycemic and paleo.",
        "packaging": "Tamper-evident stand-up foil pouch; 10 packs per master carton.",
        "storage": "Store sealed in a cool, dry pantry.",
        "allergens": "See finished pack for allergen handling statement.",
        "use": "Use for swallow, pancakes or muffins; recipe adjustments may be needed when replacing wheat flour.",
        "source": "Regional plantain farms.",
        "retail": {
            "size": "2.2 lb / 1 kg",
            "kg": 1,
            "qty": 20,
            "unit": "packs",
            "price": 5.5,
        },
    },
    {
        "id": "cocoyam",
        "name": "Traditional Cocoyam Flour",
        "size": "4.4 lb / 2 kg",
        "kg": 2,
        "qty": 10,
        "unit": "packs",
        "price": 11.5,
        "dist": 10.35,
        "initial": "CY",
        "description": "Milled cocoyam flour for traditional soups and a smooth, earthy thickening texture.",
        "ingredients": "100% dehydrated cocoyam tuber (Colocasia esculenta).",
        "diet": "Vegan, vegetarian, gluten-free, plant-based.",
        "packaging": "Resealable moisture-barrier pouch; 10 packs per master carton.",
        "storage": "Keep sealed in a dry, dark cupboard.",
        "allergens": "See finished pack for allergen handling statement.",
        "use": "Mix into a slurry and add to bitterleaf or oha soup.",
        "source": "Root-crop farms in Nigeria.",
        "retail": {
            "size": "2.2 lb / 1 kg",
            "kg": 1,
            "qty": 20,
            "unit": "packs",
            "price": 6.0,
        },
    },
    {
        "id": "sweetpotato",
        "name": "Natural Sweet Potato Flour",
        "size": "4.4 lb / 2 kg",
        "kg": 2,
        "qty": 10,
        "unit": "packs",
        "price": 12.5,
        "dist": 11.25,
        "initial": "SP",
        "description": "Gently dried sweet potato flour with natural sweetness and a soft texture.",
        "ingredients": "100% sweet potato (Ipomoea batatas).",
        "diet": "Vegan, vegetarian, grain-free, gluten-free.",
        "packaging": "Double-sealed composite stand-up pouch; 10 packs per master carton.",
        "storage": "Keep sealed in a cool, dry place.",
        "allergens": "See finished pack for allergen handling statement.",
        "use": "Use in baking blends, sauces or tortillas.",
        "source": "Local Nigerian sweet potato farms.",
        "retail": {
            "size": "2.2 lb / 1 kg",
            "kg": 1,
            "qty": 20,
            "unit": "packs",
            "price": 6.5,
        },
    },
    {
        "id": "oil",
        "name": "Premium Zomi Red Palm Oil",
        "size": "1 US gal / 3.78 L",
        "kg": None,
        "qty": 4,
        "unit": "jugs",
        "price": 21.0,
        "dist": 18.9,
        "initial": "PO",
        "description": "Pure red palm oil with a deep red colour and traditional palm fruit aroma.",
        "ingredients": "100% red palm oil (Elaeis guineensis).",
        "diet": "Vegan, vegetarian, keto-friendly, paleo, zero-carb.",
        "packaging": "Sealed food-grade HDPE jug; 4 jugs per master carton.",
        "storage": "Store at room temperature. The oil can thicken in cool conditions; warm the closed jug gently in a warm-water bath.",
        "allergens": "See finished pack for allergen handling statement.",
        "use": "Use in traditional soups, beans, rice and stews.",
        "source": "Smallholder palm orchards.",
        "retail": {
            "size": "33.8 fl oz / 1 L",
            "kg": None,
            "qty": 20,
            "unit": "bottles",
            "price": 5.5,
            "litres": 1,
        },
    },
]


def get_product(product_id: str):
    """Retrieve a single product by ID."""
    for p in PRODUCTS:
        if p["id"] == product_id:
            return p
    return None
